config/routes.rb
Markboard::Application.routes.draw do
  
  resources :pages do
    collection do 
      get 'latest'
    end
  end

  root :to => 'pages#index'
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates_presence_of :title, :message => "can't be blank"
  validates_length_of :title, :maximum => 100, :message => "is too long"
  validates_length_of :content, :maximum => 100000, :message => "is too long"

  def to_html
    options = { :autolink => true, :space_after_headers => true }
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, options).render(self.content)
  end

  def self.recent_pages
    Page.order("created_at DESC").limit(20).select("id, title")
  end

  def self.all_pages
    Page.order("updated_at DESC").select("id, title, updated_at")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter do |controller|
    controller.instance_eval do
      @recent_pages = Page.recent_pages
    end
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all_pages
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Markboard</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "shared/navbar" %>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <%= render "shared/sidebar" %>
        </div><!--/span-->
        <div class="span9">
          <div class="row-fluid">
            <%= yield %>
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Markboard 2012</p>
      </footer>

    </div><!--/.fluid-container-->

  </body>
</html>

app/views/pages/_form.html.erb
<fieldset>
  <div class="control-group">
    <div class="controls">
      <p class="help-block">The page must have a title</p>
      <%= f.text_field :title, :class => 'input-title' %>
      <%= f.text_area :content, :class => 'input-markdown' %>
    </div>
  </div>
</fieldset>

<div class="form-actions">
  <button class="btn btn-primary" type="submit">Save</button> or
	<%= link_to "Cancel", pages_path %>
</div>

app/views/pages/edit.html.erb
<%= form_for @page, :url => page_path(@page), :html => { :class => "edit_page", :id => "edit_page" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/pages/index.html.erb
<% if @pages.empty? %>
  <div class="hero-unit">
    <h3>It's time to...</h3>
    <h2><%= link_to "Create your first markdown page!", new_page_path %></h2>
  </div>
<% else %>

<h1>All Pages</h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Last Update</th>
      <th class="all-pages-actions"></th>
      </tr>
  </thead>
  <tbody>
    <% @pages.each do |page|%>
      <tr>
        <td><strong><%= link_to page.title, page %></strong></td>
        <td><%= time_ago_in_words(page.updated_at) %> ago</td>
        <td class="all-pages-actions">
          <%= link_to "Edit", edit_page_path(page), :class => 'btn btn-primary btn-small' %>
          <%= link_to "Delete", page_path(page), :method => "delete", :confirm => "Are you sure?", :class => 'btn btn-danger btn-small' %>
        </td>
      </tr>
    <% end %>  
  </tbody>
</table>
<% end %>

app/views/pages/new.html.erb
<%= form_for @page, :url => pages_path, :html => { :class => "form-horizontal" } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/pages/show.html.erb
<div class="page-header">
	<h1><%= @page.title %></h1>
</div>

<%= raw @page.to_html %>

<div class="form-actions">
<%= link_to "Edit", edit_page_path(@page), :class => 'btn btn-primary' %>
<%= link_to "Delete", page_path(@page), :method => "delete", :confirm => "Are you sure?", :class => 'btn btn-danger primary' %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="brand" href="/">Markboard</a>
      <a class="btn btn-success btn-small" href="/pages/new">
        <i class="icon-plus icon-white"></i> New Page
      </a>
      
      <a class="btn btn-small" href="/pages">
        <i class="icon-list-alt"></i> All Pages
      </a>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    
    <% if not @recent_pages.empty? %>
        <li class="nav-header">Recent Pages</li>
    <% end %>
    <% @recent_pages.each do |page| %>
        <% if @page && @page.id == page.id %>
            <li class="active"><%= link_to page.title, page %></li>
        <% else %>
            <li><%= link_to page.title, page %></li>    
        <% end %>
    <% end %>
  </ul>
</div><!--/.well -->
      